Fix: Obsolete python package on Alpine3.15
As of 10 Feb 2022, Node12-Alpine use Alpine3.15 as a base distro.
However, the python package has been removed since Alpine3.5 and replace
with python2 and python3 package.
This will cause build error:

ERROR: unable to select packages:
  python (no such package):
    required by: .build-deps-20220209.171613[python]

This patch will apply python3 package.
Test has been perform in linux/amd64 and aarch64